title: Beginner HTML & CSS Sushi Cards
hero_image: images/banner.svg
description: Learn to make a website
theme: cd-blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "animals, jokes/pranks, space, photography, music/sound, physical computing, games, robots, geography"
technologies: "html/css"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Creating a web page
  - title: Adding a stylesheet
  - title: Making a list
  - title: Adding pictures
  - title: Adding more pages
  - title: Creating links
  - title: Making a menu
  - title: Styling the menu bar
  - title: Adding a map or video
  - title: Adding a table
  - title: Download your project!
